export const surahTranslations: Record<number, string> = {
  "1": "Pembukaan",
  "2": "Sapi",
  "3": "Keluarga Imran",
  "4": "Wanita",
  "5": "Hidangan",
  "6": "Binatang Ternak",
  "7": "Tempat Tertinggi",
  "8": "Rampasan Perang",
  "9": "Pengampunan",
  "10": "Yunus",
  "11": "Hud",
  "12": "Yusuf",
  "13": "Guruh",
  "14": "Ibrahim",
  "15": "Hijr",
  "16": "Lebah",
  "17": "Memperjalankan Malam Hari",
  "18": "Goa",
  "19": "Maryam",
  "20": "Taha",
  "21": "Para Nabi",
  "22": "Haji",
  "23": "Orang-Orang Mukmin",
  "24": "Cahaya",
  "25": "Pembeda",
  "26": "Para Penyair",
  "27": "Semut-semut",
  "28": "Kisah-Kisah",
  "29": "Laba-Laba",
  "30": "Romawi",
  "31": "Luqman",
  "32": "Sajdah",
  "33": "Golongan Yang Bersekutu",
  "34": "Saba'",
  "35": "Maha Pencipta",
  "36": "Yasin",
  "37": "Barisan-Barisan",
  "38": "Sad",
  "39": "Rombongan",
  "40": "Maha Pengampun",
  "41": "Yang Dijelaskan",
  "42": "Musyawarah",
  "43": "Perhiasan",
  "44": "Kabut",
  "45": "Berlutut",
  "46": "Bukit Pasir",
  "47": "Muhammad",
  "48": "Kemenangan",
  "49": "Kamar-Kamar",
  "50": "Qaf",
  "51": "Angin yang Menerbangkan",
  "52": "Bukit Tursina",
  "53": "Bintang",
  "54": "Bulan",
  "55": "Maha Pengasih",
  "56": "Hari Kiamat",
  "57": "Besi",
  "58": "Gugatan",
  "59": "Pengusiran",
  "60": "Wanita Yang Diuji",
  "61": "Barisan",
  "62": "Jumat",
  "63": "Orang-Orang Munafik",
  "64": "Pengungkapan Kesalahan",
  "65": "Talak",
  "66": "Pengharaman",
  "67": "Kerajaan",
  "68": "Pena",
  "69": "Hari Kiamat",
  "70": "Tempat Naik",
  "71": "Nuh",
  "72": "Jin",
  "73": "Orang Yang Berselimut",
  "74": "Orang Yang Berkemul",
  "75": "Hari Kiamat",
  "76": "Manusia",
  "77": "Malaikat Yang Diutus",
  "78": "Berita Besar",
  "79": "Malaikat Yang Mencabut",
  "80": "Bermuka Masam",
  "81": "Penggulungan",
  "82": "Terbelah",
  "83": "Orang-Orang Curang",
  "84": "Terbelah",
  "85": "Gugusan Bintang",
  "86": "Yang Datang Di Malam Hari",
  "87": "Maha Tinggi",
  "88": "Hari Kiamat",
  "89": "Fajar",
  "90": "Negeri",
  "91": "Matahari",
  "92": "Malam",
  "93": "Duha",
  "94": "Lapang",
  "95": "Buah Tin",
  "96": "Segumpal Darah",
  "97": "Kemuliaan",
  "98": "Bukti Nyata",
  "99": "Guncangan",
  "100": "Kuda Yang Berlari Kencang",
  "101": "Hari Kiamat",
  "102": "Bermegah-Megahan",
  "103": "Masa",
  "104": "Pengumpat",
  "105": "Gajah",
  "106": "Quraisy",
  "107": "Barang Yang Berguna",
  "108": "Pemberian Yang Banyak",
  "109": "Orang-Orang kafir",
  "110": "Pertolongan",
  "111": "Api Yang Bergejolak",
  "112": "Ikhlas",
  "113": "Subuh",
  "114": "Manusia"
};

export const surahNamesList = [
  "al fatihah", "al baqarah", "ali 'imran", "an nisa", "al ma'idah",
  "al an'am", "al a'raf", "al anfal", "at taubah", "yunus",
  "hud", "yusuf", "ar ra'd", "ibrahim", "al hijr",
  "an nahl", "al isra", "al kahf", "maryam", "taha",
  "al anbiya", "al hajj", "al mu'minun", "an nur", "al furqan",
  "asy syu'ara", "an naml", "al qasas", "al 'ankabut", "ar rum",
  "luqman", "as sajdah", "al ahzab", "saba'", "fatir",
  "yasin", "as saffat", "sad", "az zumar", "ghafir",
  "fussilat", "asy syura", "az zukhruf", "ad dukhan", "al jasiyah",
  "al ahqaf", "muhammad", "al fath", "al hujurat", "qaf",
  "az zariyat", "at tur", "an najm", "al qamar", "ar rahman",
  "al waqi'ah", "al hadid", "al mujadilah", "al hasyr", "al mumtahanah",
  "as saff", "al jumu'ah", "al munafiqun", "at taghabun", "at talaq",
  "at tahrim", "al mulk", "al qalam", "al haqqah", "al ma'arij",
  "nuh", "al jinn", "al muzzammil", "al muddassir", "al qiyamah",
  "al insan", "al mursalat", "an naba", "an nazi'at", "'abasa",
  "at takwir", "al infitar", "al mutaffifin", "al insyiqaq", "al buruj",
  "at tariq", "al a'la", "al ghasyiyah", "al fajr", "al balad",
  "asy syams", "al lail", "ad duha", "asy syarh", "at tin",
  "al 'alaq", "al qadr", "al bayyinah", "az zalzalah", "al 'adiyat",
  "al qari'ah", "at takasur", "al 'asr", "al humazah", "al fil",
  "quraisy", "al ma'un", "al kausar", "al kafirun", "an nasr",
  "al lahab", "al ikhlas", "al falaq", "an nas"
];